os: linux

language: android

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - android-27

jdk: oraclejdk8

sudo: false

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid

cache:
  directories:
  - "$HOME/.pub-cache"

env:
- BUILD_TIME=$(date +'%Y%m%d%H%M%S') APK_PATH="${TRAVIS_TAG}_${BUILD_TIME}_hintreader.apk"

install:
- cd opengl_texture_widget_example_HINT/example
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH=./flutter/bin:$PATH
- flutter doctor
- gem install coveralls-lcov

script:
- mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
- flutter packages get

after_success:
- coveralls-lcov coverage/lcov.info
- "echo Build time: $BUILD_TIME"
- "echo Apk name: $APK_PATH"
- flutter build apk
- mv build/app/outputs/apk/release/app-release.apk $APK_PATH

deploy:
    provider: releases
    skip_cleanup: true
    file: $APK_PATH
    api_key: ${GH_TOKEN}
    on:
        branch: master
        repo: mobileappdevhm19/HINT-Reader
        tags: false


