name: opengl_texture_example
description: Demonstrates how to use the opengl_texture plugin.

dependencies:
  flutter:
    sdk: flutter

  #dependencies for database
  sqflite: ^0.12.2+1
  path_provider: ^0.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  #dependency for have an afterFirstLayout function
  after_layout: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

  opengl_texture:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/book-stack.png
    - assets/horizontalLargeDarkmode.PNG
    - assets/horizontalLargeNoDarkmode.PNG
    - assets/horizontalNormalDarkmode.PNG
    - assets/horizontalNormalNoDarkmode.PNG
    - assets/horizontalSmallDarkmode.PNG
    - assets/horizontalSmallNoDarkmode.PNG
    - assets/icon_hintreader.png
    - assets/icon_hintreader_yellow.png
    - assets/lightbulb_Hintreader_Appicon.png
    - assets/main_icon.png
    - assets/verticalLargeDarkmode.PNG
    - assets/verticalLargeNoDarkmode.PNG
    - assets/verticalNormalDarkmode.PNG
    - assets/verticalNormalNoDarkmode.PNG
    - assets/verticalSmallDarkmode.PNG
    - assets/verticalSmallNoDarkmode.PNG
    - books.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/lightbulb_Hintreader_Appicon.png"
  image_path_ios: "assets/lightbulb_Hintreader_Appicon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/ic_launcher_background.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/ic_launcher_foreground.png" # only available for Android 8.0 devices and above
